GET http://localhost:3000/actors

### show
GET http://localhost:3000/actors/3

### create
POST http://localhost:3000/actors
content-type: application/json

{
  "first_name": "Carrie",
  "last_name": "Fisher",
  "known_for": "Leia",
  "gender": "Female",
  "age": "60"
}

### update
PATCH http://localhost:3000/actors/4
content-type: application/json

{
  "director": "George Lucas",
  "english": true
}

### destroy
DELETE http://localhost:3000/actors/6


### index
GET http://localhost:3000/movies

### show
GET http://localhost:3000/movies/3

### create
POST http://localhost:3000/movies
content-type: application/json

{
  "title": "Star Wars: Attack of the Clones",
  "year": 2002,
  "plot": "Set ten years after the events of The Phantom Menace, the Republic continues to be mired in strife and chaos. A separatist movement encompassing hundreds of planets and powerful corporate alliances poses new threats to the galaxy that even the Jedi cannot stem. These moves, long planned by an as yet unrevealed and powerful force, lead to the beginning of the Clone Wars -- and the beginning of the end of the Republic.",
  "director": "George Lucas",
  "english": true
}

### update
PATCH http://localhost:3000/movies/4
content-type: application/json

{
  "director": "George Lucas",
  "english": true
}

### destroy
DELETE http://localhost:3000/movies/6